<a href="https://colab.research.google.com/github/newstage75/ML_study/blob/master/20220406Numpy%E5%85%A5%E9%96%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 最短コースでわかるPytorchから

In [1]:
#ライブラリのインポート
import numpy as np

#NumPyの浮動小数点の表示精度
np.set_printoptions(suppress=True, precision=5)

In [2]:
#array関数によるベクトル（１階配列）変数の定義
n1 = np.array([1, 2, 3, 4, 5, 6, 7])

#結果確認
print(n1)

#要素数確認
print(n1.shape)

#もう１つの方法
print(len(n1))

[1 2 3 4 5 6 7]
(7,)
7


In [3]:
#array関数による行列（２階配列）変数の定義
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]
])

#結果確認
print(n2)

#要素数確認
print(n2.shape)

#もう一つの方法
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


In [4]:
#zeros関数
n3 = np.zeros(5)
print(n3)
print(n3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
#ones関数
n4 = np.ones((2,3))

#結果確認
print(n4)

#要素数確認
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [6]:
#定数ではなく、乱数値により、NumPy変数を初期化設定
n5 = np.random.randn(2,3,4)
print(n5)
print(n5.shape)

[[[ 0.25594  1.80551 -1.54604  0.6791 ]
  [ 0.1725   0.71188  1.27324  1.07008]
  [-0.00736  2.43682 -2.43954  0.38768]]

 [[ 0.00765 -1.05289 -1.99222  2.33786]
  [-0.2095   1.48951  1.21711  1.76053]
  [ 1.46883  0.83095  0.62247 -0.64822]]]
(2, 3, 4)


In [7]:
#グラフ描画用の数値配列の生成
n6 = np.linspace(-1, 1, 11)

#結果確認
print(n6)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [8]:
#arange関数によるグラフ描画用数値配列
# 第二引数は「未満」であることに注意
n7 = np.arange(-1, 1.2, 0.2)

#結果確認
print(n7)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1. ]


##操作

In [10]:
#特定行、列の抽出(カンマより前は行の範囲を、カンマより後ろは０つの範囲を示す)

#元の変数
print(n2)

print()

#全ての行の０列を抽出
n8 = n2[:,0]
print(n8)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  4  7 10]


行要素：「：」<br>
列要素:「0」

In [11]:
#1行目と３行目を抽出
#True/Falseの要素の配列で指定する
n2_index = np.array([False, True, False, True])
n9 = n2[n2_index]
print(n9)

[[ 4  5  6]
 [10 11 12]]


Trueの列のみが抽出される。

In [13]:
#reshape関数
n10 = np.array(range(24))

#結果確認
print(n10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [14]:
#3×8の２階配列の変形
n11 = n10.reshape(3, 8)
#結果確認
print(n11)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [15]:
#reshapeは１箇所だけ「-1」値の設定が可能
n12 = n10.reshape(2, -1, 4)

#結果確認
print(n12)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
print(n12.shape)

(2, 3, 4)


In [17]:
#元々N要素のベクトルだった変数を「１行N列」の行列に変形する例
print(n10.shape)

n13 = n10.reshape(1, -1)

#結果確認
print(n13.shape)

(24,)
(1, 24)


In [18]:
# 転置行列
print(n2)

n14 = n2.T
print(n14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [19]:
#軸の順番を入れ替える

#元の変数
print(n12.shape)
print(n12)

#軸を(1, 2, 0)の順に入れ替える
n14 = np.transpose(n12, (1, 2, 0))

#結果確認
print(n14.shape)
print(n14)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [ ]:
#行列の縦連結→vstack

#行列の横連結→hstack