<a href="https://colab.research.google.com/github/newstage75/ML_study/blob/master/20220406Numpy%E5%85%A5%E9%96%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 最短コースでわかるPytorchから

In [2]:
#ライブラリのインポート
import numpy as np

#NumPyの浮動小数点の表示精度
np.set_printoptions(suppress=True, precision=5)

In [3]:
#array関数によるベクトル（１階配列）変数の定義
n1 = np.array([1, 2, 3, 4, 5, 6, 7])

#結果確認
print(n1)

#要素数確認
print(n1.shape)

#もう１つの方法
print(len(n1))

[1 2 3 4 5 6 7]
(7,)
7


In [4]:
#array関数による行列（２階配列）変数の定義
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]
])

#結果確認
print(n2)

#要素数確認
print(n2.shape)

#もう一つの方法
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


In [5]:
#zeros関数
n3 = np.zeros(5)
print(n3)
print(n3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [6]:
#ones関数
n4 = np.ones((2,3))

#結果確認
print(n4)

#要素数確認
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [7]:
#定数ではなく、乱数値により、NumPy変数を初期化設定
n5 = np.random.randn(2,3,4)
print(n5)
print(n5.shape)

[[[-0.78344  0.61074  1.61364 -0.58334]
  [ 0.36596 -0.82103 -0.70397 -0.54202]
  [-1.46257 -1.34361 -1.80218 -0.20113]]

 [[-0.31272  1.06599 -0.07725  0.71809]
  [ 0.33436  0.73115  0.2549  -1.3984 ]
  [ 0.02997  0.04765  0.57767 -1.67144]]]
(2, 3, 4)


In [8]:
#グラフ描画用の数値配列の生成
n6 = np.linspace(-1, 1, 11)

#結果確認
print(n6)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [9]:
#arange関数によるグラフ描画用数値配列
# 第二引数は「未満」であることに注意
n7 = np.arange(-1, 1.2, 0.2)

#結果確認
print(n7)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1. ]


##操作

In [10]:
#特定行、列の抽出(カンマより前は行の範囲を、カンマより後ろは０つの範囲を示す)

#元の変数
print(n2)

print()

#全ての行の０列を抽出
n8 = n2[:,0]
print(n8)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  4  7 10]


行要素：「：」<br>
列要素:「0」

In [11]:
#1行目と３行目を抽出
#True/Falseの要素の配列で指定する
n2_index = np.array([False, True, False, True])
n9 = n2[n2_index]
print(n9)

[[ 4  5  6]
 [10 11 12]]


Trueの列のみが抽出される。

In [12]:
#reshape関数
n10 = np.array(range(24))

#結果確認
print(n10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [13]:
#3×8の２階配列の変形
n11 = n10.reshape(3, 8)
#結果確認
print(n11)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [14]:
#reshapeは１箇所だけ「-1」値の設定が可能
n12 = n10.reshape(2, -1, 4)

#結果確認
print(n12)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [15]:
print(n12.shape)

(2, 3, 4)


In [16]:
#元々N要素のベクトルだった変数を「１行N列」の行列に変形する例
print(n10.shape)

n13 = n10.reshape(1, -1)

#結果確認
print(n13.shape)

(24,)
(1, 24)


In [17]:
# 転置行列
print(n2)

n14 = n2.T
print(n14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [18]:
#軸の順番を入れ替える

#元の変数
print(n12.shape)
print(n12)

#軸を(1, 2, 0)の順に入れ替える
n14 = np.transpose(n12, (1, 2, 0))

#結果確認
print(n14.shape)
print(n14)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [19]:
#行列の縦連結→vstack

#行列の横連結→hstack


#２行３列
n16 = np.array(range(1, 7)).reshape(2,3)
n17 = np.array(range(7, 13)).reshape(2,3)

#3要素のベクトル
n18 = np.array(range(14,17))

#2要素のベクトル
n19 = np.array(range(17,19))

print(n16)
print(n17)
print(n18)
print(n19)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[14 15 16]
[17 18]


In [20]:
#行同士の縦結合
n20 = np.vstack([n16, n17])
print(n20)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
#行列とベクトル間の縦結合
n21 = np.vstack([n16, n18])
print(n21)

[[ 1  2  3]
 [ 4  5  6]
 [14 15 16]]


In [22]:
#行列同士の横連結
n22 = np.hstack([n16, n17])
print(n22)

#行列とベクトル間の横連結
#ベクトルのshapeを(N, 1)形式にする
n23 = n19.reshape(-1, 1)
n24 = np.hstack([n16, n23])
print(n24)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3 17]
 [ 4  5  6 18]]
