<a href="https://colab.research.google.com/github/newstage75/ML_study/blob/master/%E6%9C%80%E7%9F%ADPytorch/%EF%BC%91%E7%AB%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#お決まり部分
最初の宣言

In [3]:
# 必要ライブラリの導入

!pip install japanize_matplotlib | tail -n 1

In [4]:
# 必要ライブラリのインポート

%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib

In [5]:
# warning表示off
import warnings
warnings.simplefilter('ignore')

# デフォルトフォントサイズ変更
plt.rcParams['font.size'] = 14

# デフォルトグラフサイズ変更
plt.rcParams['figure.figsize'] = (6,6)

# デフォルトで方眼表示ON
plt.rcParams['axes.grid'] = True

# numpyの表示桁数設定
np.set_printoptions(suppress=True, precision=5)

In [6]:
x = np.array([5, 7, 9])

y = x

print(x)
print(y)

[5 7 9]
[5 7 9]


In [7]:
x[1] = -1

print(x)
print(y)

[ 5 -1  9]
[ 5 -1  9]


In [8]:
#yも同時に変化して困る場合は、大乳児にcopy関数を利用する
x = np.array([5, 7, 9])
y = x.copy()

#すると、xの特定の要素値の変更がyに影響しなくなる
x[1] = -1

print(x)
print(y)

[ 5 -1  9]
[5 7 9]


In [10]:
import torch

#x1:shape=[5]となるすべて値が１のテンソル
x1 = torch.ones(5)

print(x1)

#x2:x1から生成したNumPy
x2 = x1.data.numpy()

#結果確認
print(x2)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [11]:
x1[1] = -1

print(x1)
print(x2)

tensor([ 1., -1.,  1.,  1.,  1.])
[ 1. -1.  1.  1.  1.]


In [12]:
#安全な方法

#x1:テンソル
x1 = torch.ones(5)

#2:x1をcopyしたNumPy
x2 = x1.data.numpy().copy()

x1[1] = -1

print(x1)
print(x2)

tensor([ 1., -1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]
